### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by andlo** [nickknissen/hass-monta#125]
### System Health details

n/a

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nickknissen/hass-monta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Today the integration failed to setup.
I did delet it and tryed to setup again, but same result

### Reproduction steps

setup the integration

### Debug logs

```text
...
```

### Diagnostics dump

[home-assistant_monta_2024-10-16T13-20-05.574Z.log](https://github.com/user-attachments/files/17396634/home-assistant_monta_2024-10-16T13-20-05.574Z.log)

**Comment by andlo** [comment]
It seems to fail in setup wallet transactions....
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/monta/coordinator.py", line 40, in _async_update_data
    wallet = await self.client.async_get_wallet_transactions()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/monta/api.py", line 180, in async_get_wallet_transactions
    return sorted(response["data"], key=lambda transaction: -transaction["id"])
                  ~~~~~~~~^^^^^^^^
KeyError: 'data'
2024-10-16 15:19:59.882 DEBUG (MainThread) [custom_components.monta] Finished fetching monta data in 0.594 seconds (success: False)
`
Which seems to be a error in Monta backend https://status.monta.app/incidents/rlkv19vbkz0n

**Comment by andlo** [comment]
I did comment out line 172 to 180 in api.py to get it gooing - obversly I will not get any wallet transactions.

![image](https://github.com/user-attachments/assets/7b40a259-3cb9-40b9-aa99-ff09b7a5d087)

**Comment by Symbiot78** [comment]
the incident says it's resolved, but the setup still fails. 

this is the debug error it throws..

`2024-10-16 20:06:43.880 DEBUG (MainThread) [custom_components.monta.api] No token is valid, Requesting a new tokens
2024-10-16 20:06:43.931 DEBUG (MainThread) [custom_components.monta.api] [auth/token] Response header: <CIMultiDictProxy('Date': 'Wed, 16 Oct 2024 18:06:43 GMT', 'Content-Type': 'application/json', 'Content-Length': '264', 'Connection': 'keep-alive', 'request-id': '89492dc1-a70a-4ded-9542-96fff871b531', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains')>
2024-10-16 20:06:43.931 DEBUG (MainThread) [custom_components.monta.api] [auth/token] Response status: 200
2024-10-16 20:06:43.931 DEBUG (MainThread) [custom_components.monta.api] [auth/token] Response body : {'applicationId': 43, 'userId': 6211, 'accessToken': '************************************', 'accessTokenExpirationDate': '2024-10-16T19:06:43.907170726Z', 'refreshToken': '************************************', 'refreshTokenExpirationDate': '2024-11-15T18:06:43.907174515Z'}
2024-10-16 20:06:44.030 DEBUG (MainThread) [custom_components.monta.api] [charge-points?page=0&perPage=10] Response header: <CIMultiDictProxy('Date': 'Wed, 16 Oct 2024 18:06:44 GMT', 'Content-Type': 'application/json', 'Content-Length': '781', 'Connection': 'keep-alive', 'request-id': '5c223d15-0ce6-4002-b963-b580b2cad1ae', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains')>
2024-10-16 20:06:44.030 DEBUG (MainThread) [custom_components.monta.api] [charge-points?page=0&perPage=10] Response status: 200
2024-10-16 20:06:44.030 DEBUG (MainThread) [custom_components.monta.api] [charge-points?page=0&perPage=10] Response body : {'data': [{'id': 275445, 'createdAt': '2021-10-10T16:24:56Z', 'updatedAt': '2024-10-16T01:48:18Z', 'serialNumber': '*********', 'name': 'Skalhøje 81', 'visibility': 'private', 'maxKW': 11.0, 'maxKw': 11.0, 'type': 'ac', 'note': 'if I’m parked in the carport, just give a knock - I’ll move my car👍', 'state': 'available', 'location': {'coordinates': {'latitude': '**********', 'longitude': '*********'}, 'address': {'address1': '***********', 'address2': '*********', 'address3': '****', 'zip': '9240', 'city': 'Nibe', 'country': 'Denmark'}}, 'connectors': [{'identifier': 'ccs', 'name': 'CCS'}], 'lastMeterReadingKwh': 12943.557, 'cablePluggedIn': True, 'brandName': 'Zaptec', 'modelName': 'Zaptec - Go', 'firmwareVersion': '2.4.1.0'}], 'meta': {'itemCount': 1, 'currentPage': 0, 'perPage': 10, 'totalPageCount': 1, 'totalItemCount': 1}}
2024-10-16 20:06:44.031 DEBUG (MainThread) [custom_components.monta.api] Access Token still valid, using it
2024-10-16 20:06:44.304 DEBUG (MainThread) [custom_components.monta.api] [charges?chargePointId=275445] Response header: <CIMultiDictProxy('Date': 'Wed, 16 Oct 2024 18:06:44 GMT', 'Content-Type': 'application/json', 'Content-Length': '1064', 'Connection': 'keep-alive', 'request-id': '4a9b5547-c7f0-474f-8404-a6d2295e3501', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains')>
2024-10-16 20:06:44.304 DEBUG (MainThread) [custom_components.monta.api] [charges?chargePointId=275445] Response status: 200
2024-10-16 20:06:44.305 DEBUG (MainThread) [custom_components.monta.api] [charges?chargePointId=275445] Response body : {'data': [{'id': 633061405767924232, 'chargePointId': 275445, 'createdAt': '2024-10-12T22:00:00Z', 'updatedAt': '2024-10-13T04:00:08Z', 'cablePluggedInAt': '2024-10-12T22:00:00Z', 'startedAt': '2024-10-12T22:00:01Z', 'stoppedAt': '2024-10-13T04:00:02Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 61.01, 'kwhLimit': None, 'startMeterKwh': 12882.55, 'endMeterKwh': 12943.557, 'cost': 8.29, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 92.44, 'averageRenewablePerKwh': 86.84, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 630887078771633488, 'chargePointId': 275445, 'createdAt': '2024-10-06T22:00:00Z', 'updatedAt': '2024-10-07T03:00:24Z', 'cablePluggedInAt': '2024-10-06T22:00:00Z', 'startedAt': '2024-10-06T22:00:01Z', 'stoppedAt': '2024-10-07T03:00:01Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 51.77, 'kwhLimit': None, 'startMeterKwh': 12830.783, 'endMeterKwh': 12882.55, 'cost': 23.31, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 121.78, 'averageRenewablePerKwh': 86.63, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 630675686628855826, 'chargePointId': 275445, 'createdAt': '2024-10-06T08:00:01Z', 'updatedAt': '2024-10-06T09:40:30Z', 'cablePluggedInAt': '2024-10-06T08:00:01Z', 'startedAt': '2024-10-06T08:00:01Z', 'stoppedAt': '2024-10-06T09:40:29Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 18.49, 'kwhLimit': None, 'startMeterKwh': 12812.284, 'endMeterKwh': 12830.773, 'cost': 12.42, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 89.27, 'averageRenewablePerKwh': 92.44, 'failureReason': None, 'stopReason': 'api', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 629437542150768964, 'chargePointId': 275445, 'createdAt': '2024-10-02T22:00:04Z', 'updatedAt': '2024-10-03T03:04:45Z', 'cablePluggedInAt': '2024-10-02T22:00:04Z', 'startedAt': '2024-10-02T22:00:05Z', 'stoppedAt': '2024-10-03T03:04:43Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 53.83, 'kwhLimit': None, 'startMeterKwh': 12758.454, 'endMeterKwh': 12812.284, 'cost': 40.2, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 74.19, 'averageRenewablePerKwh': 91.25, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 18746554, 'chargePointId': 275445, 'createdAt': '2024-09-28T22:00:02Z', 'updatedAt': '2024-09-28T23:00:04Z', 'cablePluggedInAt': '2024-09-28T22:00:02Z', 'startedAt': '2024-09-28T22:00:03Z', 'stoppedAt': '2024-09-28T23:00:01Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 10.97, 'kwhLimit': None, 'startMeterKwh': 12747.473, 'endMeterKwh': 12758.447, 'cost': 5.26, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 103.0, 'averageRenewablePerKwh': 84.93, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 18702511, 'chargePointId': 275445, 'createdAt': '2024-09-27T22:00:04Z', 'updatedAt': '2024-09-28T05:00:03Z', 'cablePluggedInAt': '2024-09-27T22:00:04Z', 'startedAt': '2024-09-27T22:00:04Z', 'stoppedAt': '2024-09-28T05:00:01Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 71.5, 'kwhLimit': None, 'startMeterKwh': 12675.973, 'endMeterKwh': 12747.473, 'cost': 12.65, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 78.06, 'averageRenewablePerKwh': 92.14, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 18470867, 'chargePointId': 275445, 'createdAt': '2024-09-23T22:00:01Z', 'updatedAt': '2024-09-24T05:00:11Z', 'cablePluggedInAt': '2024-09-23T22:00:01Z', 'startedAt': '2024-09-23T22:00:01Z', 'stoppedAt': '2024-09-24T05:00:01Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 61.26, 'kwhLimit': None, 'startMeterKwh': 12614.716, 'endMeterKwh': 12675.973, 'cost': 56.89, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 140.23, 'averageRenewablePerKwh': 81.59, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 18100411, 'chargePointId': 275445, 'createdAt': '2024-09-16T20:00:01Z', 'updatedAt': '2024-09-17T02:08:30Z', 'cablePluggedInAt': '2024-09-16T20:00:01Z', 'startedAt': '2024-09-16T20:00:01Z', 'stoppedAt': '2024-09-17T02:08:28Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 65.7, 'kwhLimit': None, 'startMeterKwh': 12549.013, 'endMeterKwh': 12614.716, 'cost': 60.51, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 166.95, 'averageRenewablePerKwh': 80.19, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 17797530, 'chargePointId': 275445, 'createdAt': '2024-09-10T21:00:01Z', 'updatedAt': '2024-09-11T04:00:07Z', 'cablePluggedInAt': '2024-09-10T21:00:01Z', 'startedAt': '2024-09-10T21:00:04Z', 'stoppedAt': '2024-09-11T04:00:01Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 64.44, 'kwhLimit': None, 'startMeterKwh': 12484.577, 'endMeterKwh': 12549.013, 'cost': 22.38, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 77.05, 'averageRenewablePerKwh': 86.06, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}, {'id': 17555359, 'chargePointId': 275445, 'createdAt': '2024-09-06T04:02:48Z', 'updatedAt': '2024-09-06T05:00:09Z', 'cablePluggedInAt': '2024-09-06T04:02:48Z', 'startedAt': '2024-09-06T04:02:48Z', 'stoppedAt': '2024-09-06T05:00:02Z', 'fullyChargedAt': None, 'failedAt': None, 'timeoutAt': None, 'state': 'completed', 'consumedKwh': 0.0, 'kwhLimit': None, 'startMeterKwh': 12484.577, 'endMeterKwh': 12484.577, 'cost': 0, 'price': 0, 'priceLimit': None, 'averagePricePerKwh': 0, 'averageCo2PerKwh': 0.0, 'averageRenewablePerKwh': 0.0, 'failureReason': None, 'stopReason': 'StoppedByUser', 'note': None, 'currency': {'identifier': 'dkk', 'name': 'Danish kroner', 'decimals': 2}, 'soc': None, 'socLimit': None}], 'meta': {'itemCount': 10, 'currentPage': 0, 'perPage': 10, 'totalPageCount': 48, 'totalItemCount': 471}}
2024-10-16 20:06:44.305 DEBUG (MainThread) [custom_components.monta.api] Access Token still valid, using it
2024-10-16 20:06:44.416 DEBUG (MainThread) [custom_components.monta.api] [wallet-transactions] Response header: <CIMultiDictProxy('Date': 'Wed, 16 Oct 2024 18:06:44 GMT', 'Content-Type': 'application/json', 'Content-Length': '101', 'Connection': 'keep-alive', 'request-id': '04daf87b-59fc-46a7-8872-561400a9ccbc', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains')>
2024-10-16 20:06:44.416 DEBUG (MainThread) [custom_components.monta.api] [wallet-transactions] Response status: 200
2024-10-16 20:06:44.416 DEBUG (MainThread) [custom_components.monta.api] [wallet-transactions] Response body : {'status': 'OK', 'message': 'Unknown Error', 'readableMessage': None, 'errorCode': 'UNKNOWN', 'context': None}
2024-10-16 20:06:44.416 ERROR (MainThread) [custom_components.monta] Unexpected error fetching monta data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/monta/coordinator.py", line 40, in _async_update_data
    wallet = await self.client.async_get_wallet_transactions()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/monta/api.py", line 180, in async_get_wallet_transactions
    return sorted(response["data"], key=lambda transaction: -transaction["id"])
                  ~~~~~~~~^^^^^^^^
KeyError: 'data'
2024-10-16 20:06:44.417 DEBUG (MainThread) [custom_components.monta] Finished fetching monta data in 0.538 seconds (success: False)`

**Comment by nickknissen** [comment]
I am on vacation without any computer. But I will look into the issue when I get back.

**Comment by michaeltryl** [comment]
I just follow this to see if there come any solution :)

**Comment by RuneNyhuus** [comment]
I have the same error as above :)
